### ISSUE TITLE
Backing up Cisco Wireless Controller

### ISSUE THREAD

**Issue by did8** [earendilfr/rancid#2]
Hi,

I am having an issue with the configuration backup of cisco wireless controller with Rancid.
I am able to login using .clogin by running the command: 
/usr/lib/rancid/bin/clogin -f /var/lib/rancid/.cloginrc 192.168.1.5
i can see the prompt. However, rancid is not downloading the configuration. 
Is there anything else i am missing?

**Comment by earendilfr** [comment]
To reach a Cisco WLC controler, you should use the **wlogin** and not clogin (not the same comands set).

If you want to be sure to use the right script to connect to a device and you have already add it to Rancid router.db, you can use the plogin script that search in the router.db and use the "*login" script that correspond to the type of device.
