### ISSUE TITLE
panos/pm panlogin configuration mode prompt

### ISSUE THREAD

**Issue by Seethaar** [earendilfr/rancid#3]
Hi there,

I am trying use rancid to backup running-configuration palo alto firewalls in xml format. The panos.pm has got a subroutine 'ShowConfig' which backs the configuration in the default format. 

Though PA has no 'enable mode' like cisco, it has 'Configuration mode', getting into which I can retrieve the running-configuration  in xml format using **panlogin** command like this.

panlogin -t 90 -c"set cli scripting-mode on;set cli pager off;set cli config-output-format xml;**configure**;show;exit;" <firewall IP>

The problem is I have no way of replicating in this /etc/rancid/rancid.types.conf.

I tried something like this but in vain. It would run those commands, but not back up anything. Rancid process is going to get stuck in the CLI.

paloalto2;script;rancid -t paloalto2
paloalto2;login;panlogin
paloalto2;module;panos
paloalto2;inloop;panos::inloop
paloalto2;command;rancid::RunCommand;set cli scripting-mode on
paloalto2;command;rancid::RunCommand;set cli pager off
paloalto2;command;rancid::RunCommand;set cli config-output-format xml
paloalto2;command;rancid::RunCommand;configure
paloalto2;command;rancid::RunCommand;show
paloalto2;command;rancid::RunCommand;exit

Do you have any ideas ?

**Comment by earendilfr** [comment]
Hi,

Could you provide me the output of the command rancid -d -t paloalto2 <your device> ?

Regards

**Comment by earendilfr** [comment]
No more news.
Check if still the case in Rancid 3.9
